py_binary(
    name = "hello",
    srcs = ["hello.py"],
    deps = ["//utils:math_utils"],
)

py_test(
    name = "hello_test",
    srcs = ["hello_test.py"],
    deps = [
        "//utils:math_utils",
    ],
)
