py_library(
    name = "math_utils",
    srcs = ["math.py"],
    visibility = ["//visibility:public"],
)

py_test(
    name = "math_test",
    srcs = ["math_test.py"],
    deps = ["//utils:math_utils"],
)

